# Generated by Django 6.0.7 on 2026-09-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.JSONField(blank=True, default=list),
        ),
    ]