# Generated by Django 6.0.7 on 2026-09-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('agent_manager', 'Agent Manager'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
