import { useEffect, useMemo, useState } from 'react';
import { FiBarChart2, FiCheckCircle, FiClock, FiInbox } from 'react-icons/fi';
import API from '../../api/auth';

export default function ManagerReports() {
  const [tickets, setTickets] = useState([]);
  useEffect(() => { API.get('/manager/unassigned-tickets/?scope=all').then((response) => setTickets(Array.isArray(response.data) ? response.data : [])).catch(() => setTickets([])); }, []);
  const stats = useMemo(() => ({ resolved: tickets.filter((ticket) => ['RESOLVED', 'CLOSED', 'AI_RESOLVED'].includes(ticket.status)).length, escalated: tickets.filter((ticket) => ['ESCALATED', 'PENDING_HUMAN_REVIEW'].includes(ticket.status)).length, highPriority: tickets.filter((ticket) => ['HIGH', 'URGENT'].includes(ticket.priority)).length }), [tickets]);
  const rate = tickets.length ? Math.round((stats.resolved / tickets.length) * 100) : 0;
  return <div className="mx-auto max-w-7xl space-y-6"><header className="rounded-[18px] border border-[#dfe5e1] bg-white px-5 py-5 shadow-sm"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-wide text-[#8b95a1]"><FiBarChart2 className="text-[#14532d]" /> Operations analytics</div><h1 className="mt-1 text-[24px] font-bold text-[#1c2430]">Reports</h1><p className="mt-1 text-[12px] text-[#64748b]">A live snapshot of ticket volume, resolution progress, and operational risk.</p></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[FiInbox, 'Total tickets', tickets.length, 'All ticket records'], [FiCheckCircle, 'Resolved / closed', stats.resolved, `${rate}% resolution rate`], [FiClock, 'High priority', stats.highPriority, 'High or urgent tickets'], [FiBarChart2, 'Escalated', stats.escalated, 'Needs manager attention']].map(([Icon, label, value, helper]) => <div key={label} className="rounded-[14px] border border-[#dfe5e1] bg-white p-4 shadow-sm"><div className="flex items-start justify-between"><div><div className="text-[10px] font-bold uppercase tracking-wide text-[#8b95a1]">{label}</div><div className="mt-2 text-3xl font-extrabold text-[#1c2430]">{value}</div><div className="mt-1 text-[11px] text-[#64748b]">{helper}</div></div><Icon className="mt-1 text-[#14532d]" /></div></div>)}</div><section className="rounded-[14px] border border-[#dfe5e1] bg-white p-5 shadow-sm"><h2 className="text-[15px] font-bold text-[#1c2430]">Manager focus areas</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-[#f8faf9] p-4"><div className="text-[11px] font-bold uppercase text-[#64748b]">Resolution progress</div><div className="mt-2 h-2 rounded-full bg-[#e5ebe7]"><div className="h-2 rounded-full bg-[#198754]" style={{ width: `${rate}%` }} /></div><p className="mt-2 text-[11px] text-[#64748b]">Keep resolved work moving through closure.</p></div><div className="rounded-xl bg-[#f8faf9] p-4"><div className="text-[11px] font-bold uppercase text-[#64748b]">Escalation watch</div><p className="mt-2 text-2xl font-bold text-[#1c2430]">{stats.escalated}</p><p className="text-[11px] text-[#64748b]">Tickets requiring review.</p></div><div className="rounded-xl bg-[#f8faf9] p-4"><div className="text-[11px] font-bold uppercase text-[#64748b]">Data freshness</div><p className="mt-2 text-sm font-bold text-emerald-700">Live workspace data</p><p className="text-[11px] text-[#64748b]">Refresh the console for the latest counts.</p></div></div></section></div>;
}
