import { useState } from 'react';
import { FiBell, FiCheckCircle, FiSettings, FiShield } from 'react-icons/fi';
import { toast } from 'react-toastify';

export default function ManagerSettings() {
  const [settings, setSettings] = useState({ autoAssign: true, alerts: true, sla: '4' });
  const update = (key, value) => setSettings((current) => ({ ...current, [key]: value }));
  const save = (event) => { event.preventDefault(); localStorage.setItem('managerSettings', JSON.stringify(settings)); toast.success('Manager preferences saved'); };
  return <div className="mx-auto max-w-4xl space-y-6"><header className="rounded-[18px] border border-[#dfe5e1] bg-white px-5 py-5 shadow-sm"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-wide text-[#8b95a1]"><FiSettings className="text-[#14532d]" /> Workspace preferences</div><h1 className="mt-1 text-[24px] font-bold text-[#1c2430]">Settings</h1><p className="mt-1 text-[12px] text-[#64748b]">Tune assignment behavior and manager notifications for this workspace.</p></header><form onSubmit={save} className="rounded-[14px] border border-[#dfe5e1] bg-white shadow-sm"><div className="border-b border-[#dfe5e1] px-5 py-4"><h2 className="text-[15px] font-bold text-[#1c2430]">Manager controls</h2></div><div className="divide-y divide-[#eef2f0]"><label className="flex items-center justify-between gap-4 px-5 py-5"><span className="flex items-start gap-3"><FiShield className="mt-0.5 text-[#14532d]" /><span><span className="block text-[13px] font-semibold text-[#1c2430]">Skill-based auto-assignment</span><span className="mt-1 block text-[11px] text-[#64748b]">Use agent expertise when routing newly created tickets.</span></span></span><input type="checkbox" checked={settings.autoAssign} onChange={(event) => update('autoAssign', event.target.checked)} className="h-4 w-4 accent-emerald-700" /></label><label className="flex items-center justify-between gap-4 px-5 py-5"><span className="flex items-start gap-3"><FiBell className="mt-0.5 text-[#14532d]" /><span><span className="block text-[13px] font-semibold text-[#1c2430]">Escalation alerts</span><span className="mt-1 block text-[11px] text-[#64748b]">Notify me when tickets need human review or approach SLA breach.</span></span></span><input type="checkbox" checked={settings.alerts} onChange={(event) => update('alerts', event.target.checked)} className="h-4 w-4 accent-emerald-700" /></label><label className="flex items-center justify-between gap-4 px-5 py-5"><span><span className="block text-[13px] font-semibold text-[#1c2430]">SLA warning threshold</span><span className="mt-1 block text-[11px] text-[#64748b]">Alert this many hours before a ticket deadline.</span></span><select value={settings.sla} onChange={(event) => update('sla', event.target.value)} className="rounded-lg border border-[#dfe5e1] px-3 py-2 text-[12px]"><option value="1">1 hour</option><option value="2">2 hours</option><option value="4">4 hours</option></select></label></div><div className="flex justify-end border-t border-[#dfe5e1] px-5 py-4"><button type="submit" className="inline-flex items-center gap-2 rounded-lg bg-[#14532d] px-4 py-2.5 text-[12px] font-bold text-white hover:bg-[#0f3e22]"><FiCheckCircle /> Save preferences</button></div></form></div>;
}
